tls_server_config:
    cert_file: "{{ node_exporter.config_dir }}/ssl/cert.pem"
    key_file: "{{ node_exporter.config_dir }}/ssl/key.pem"
    client_auth_type: "RequireAndVerifyClientCert"
    client_ca_file: "{{ node_exporter.config_dir }}/ssl/ca.pem"
