- name: generate private key
  community.crypto.openssl_privatekey:
    path: "{{ work_dir | default(playbook_dir + '/tmp') }}/{{ service_name }}-intermediate.key"
    type: RSA
    size: 2048
    state: present
    mode: 0600
  delegate_to: localhost
  run_once: true

- name: generate csr
  community.crypto.openssl_csr:
    path: "{{ work_dir | default(playbook_dir + '/tmp') }}/{{ service_name }}-intermediate.csr"
    privatekey_path: "{{ work_dir | default(playbook_dir + '/tmp') }}/{{ service_name }}-intermediate.key"
    common_name: "{{ service_name }} Intermediate CA"
    basic_constraints:
      - CA:TRUE
      - pathlen:0
    key_usage:
      - digitalSignature
      - keyCertSign
    state: present
    mode: 0600
  delegate_to: localhost
  run_once: true

- name: generate crt
  community.crypto.x509_certificate:
    path: "{{ work_dir | default(playbook_dir + '/tmp') }}/{{ service_name }}-intermediate.crt"
    privatekey_path: "{{ work_dir | default(playbook_dir + '/tmp') }}/{{ service_name }}-intermediate.key"
    csr_path: "{{ work_dir | default(playbook_dir + '/tmp') }}/{{ service_name }}-intermediate.csr"
    provider: ownca
    ownca_path: "{{ work_dir | default(playbook_dir + '/tmp') }}/ca.crt"
    ownca_privatekey_path: "{{ work_dir | default(playbook_dir + '/tmp') }}/ca.key"
    mode: 0644
  delegate_to: localhost
  run_once: true
