- name: generate intermediate certificate
  ansible.builtin.include_role:
    name: certificates/intermediate
  vars:
    service_name: prometheus

- name: create local certificate directory
  ansible.builtin.file:
    path: "{{ work_dir | default(playbook_dir + '/tmp') }}/{{ inventory_hostname }}"
    state: directory
    mode: 0700
  delegate_to: localhost

- name: generate private key
  community.crypto.openssl_privatekey:
    path: "{{ work_dir | default(playbook_dir + '/tmp') }}/{{ inventory_hostname }}/grafana-prometheus-client.key"
    type: RSA
    size: 2048
    state: present
    mode: 0600
  delegate_to: localhost
  register: key

- name: generate csr
  community.crypto.openssl_csr:
    path: "{{ work_dir | default(playbook_dir + '/tmp') }}/{{ inventory_hostname }}/grafana-prometheus-client.csr"
    privatekey_path: "{{ work_dir | default(playbook_dir + '/tmp') }}/{{ inventory_hostname }}/grafana-prometheus-client.key"
    common_name: prometheus - client
    key_usage:
      - digitalSignature
    extended_key_usage:
      - clientAuth
    state: present
    mode: 0600
  delegate_to: localhost

- name: generate crt
  community.crypto.x509_certificate:
    path: "{{ work_dir | default(playbook_dir + '/tmp') }}/{{ inventory_hostname }}/grafana-prometheus-client.crt"
    privatekey_path: "{{ work_dir | default(playbook_dir + '/tmp') }}/{{ inventory_hostname }}/grafana-prometheus-client.key"
    csr_path: "{{ work_dir | default(playbook_dir + '/tmp') }}/{{ inventory_hostname }}/grafana-prometheus-client.csr"
    provider: ownca
    ownca_path: "{{ work_dir | default(playbook_dir + '/tmp') }}/prometheus-intermediate.crt"
    ownca_privatekey_path: "{{ work_dir | default(playbook_dir + '/tmp') }}/prometheus-intermediate.key"
    mode: 0644
  delegate_to: localhost

- command: cat "{{ work_dir | default(playbook_dir + '/tmp') }}/prometheus-intermediate.crt"
  register: ca
  delegate_to: localhost

- command: cat "{{ work_dir | default(playbook_dir + '/tmp') }}/{{ inventory_hostname }}/grafana-prometheus-client.crt"
  register: cert
  delegate_to: localhost

- command: cat "{{ work_dir | default(playbook_dir + '/tmp') }}/{{ inventory_hostname }}/grafana-prometheus-client.key"
  register: key
  delegate_to: localhost

- name: copy datasources
  ansible.builtin.template:
    src: templates/datasources/prometheus.yaml
    dest: "{{ grafana.config_dir }}/provisioning/datasources/prometheus.yaml"
    owner: "{{ grafana.user }}"
    group: "{{ grafana.group }}"
    mode: 0600
  become: true
  notify: restart grafana
