- name: create group {{ prometheus.group }}
  ansible.builtin.group:
    name: "{{ prometheus.group }}"
    system: true
    state: present
  become: true

- name: create user {{ prometheus.user }}
  ansible.builtin.user:
    name: "{{ prometheus.user }}"
    group: "{{ prometheus.group }}"
    shell: /usr/bin/nologin
    home: "{{ prometheus.data_dir }}"
    create_home: false
    state: present
  become: true

- name: create directories
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    owner: "{{ prometheus.user }}"
    group: "{{ prometheus.group }}"
    mode: 0700
  with_items:
    - "{{ prometheus.config_dir }}"
    - "{{ prometheus.data_dir }}"
  become: true

- name: get prometheus
  ansible.builtin.get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v{{ prometheus.version }}/prometheus-{{ prometheus.version }}.linux-amd64.tar.gz
    dest: "{{ work_dir | default(playbook_dir + '/tmp') }}/prometheus-{{ prometheus.version }}.linux-amd64.tar.gz"
    checksum: sha256:{{ prometheus.checksum }}
  delegate_to: localhost
  run_once: true

- name: extract archive
  unarchive:
    src: "{{ work_dir | default(playbook_dir + '/tmp') }}/prometheus-{{ prometheus.version }}.linux-amd64.tar.gz"
    dest: "{{ work_dir | default(playbook_dir + '/tmp') }}"
  delegate_to: localhost
  run_once: true

- name: copy binary
  ansible.builtin.copy:
    src: "{{ work_dir | default(playbook_dir + '/tmp') }}/prometheus-{{ prometheus.version }}.linux-amd64/{{ item }}"
    dest: /usr/local/bin/{{ item }}
    owner: root
    group: root
    mode: 0755
  with_items:
    - prometheus
    - promtool
  become: true
  notify: restart prometheus

- name: copy config
  ansible.builtin.template:
    src: templates/{{ item.src }}
    dest: "{{ prometheus.config_dir }}/{{ item.dest }}"
    owner: "{{ prometheus.user }}"
    group: "{{ prometheus.group }}"
    mode: 0600
  with_items:
    - src: prometheus.yml
      dest: prometheus.yml
    - src: web-config.yml
      dest: web-config.yml
  become: true
  notify: restart prometheus

- name: configure certificates
  include_tasks: certificates.yml

- name: copy service
  ansible.builtin.template:
    src: templates/prometheus.service
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: 0644
  become: true
  notify: restart prometheus

- name: start service
  ansible.builtin.systemd:
    name: prometheus
    state: started
    enabled: true
    daemon_reload: true
  become: true

- name: configure consul service
  include_tasks: consul.yml
  when: consul is defined
