- name: install dependencies
  package:
    name: "{{ dependency }}"
    state: present
  loop: "{{ golang.dependencies }}"
  loop_control:
    loop_var: dependency
  become: true

- name: get archive
  ansible.builtin.get_url:
    url: https://go.dev/dl/go1.18.1.linux-amd64.tar.gz
    dest: "{{ work_dir | default(playbook_dir + '/tmp') }}/go1.18.1.linux-amd64.tar.gz"
    checksum: sha256:b3b815f47ababac13810fc6021eb73d65478e0b2db4b09d348eefad9581a2334

- name: unarchive
  unarchive:
    src: "{{ work_dir | default(playbook_dir + '/tmp') }}/go1.18.1.linux-amd64.tar.gz"
    dest: "{{ golang.goroot }}"
    remote_src: true

- name: register go in {{ ansible_env.HOME }}/.bashrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "{{ line }}"
    state: present
  loop:
    - export PATH=$PATH:{{ golang.goroot }}/go/bin
    - export GOROOT={{ golang.goroot }}/go
  loop_control:
    loop_var: line
