- name: generate private key
  community.crypto.openssl_privatekey:
    path: "{{ work_dir | default(playbook_dir + '/tmp') }}/kube-controller-manager.key"
    type: RSA
    size: 2048
    state: present
    mode: 0600
  delegate_to: localhost
  run_once: true

- name: generate csr
  community.crypto.openssl_csr:
    path: "{{ work_dir | default(playbook_dir + '/tmp') }}/kube-controller-manager.csr"
    privatekey_path: "{{ work_dir | default(playbook_dir + '/tmp') }}/kube-controller-manager.key"
    common_name: "system:kube-controller-manager"
    organization_name: "system:kube-controller-manager"
    key_usage:
      - digitalSignature
    extended_key_usage:
      - serverAuth
      - clientAuth
    state: present
    mode: 0600
  delegate_to: localhost
  run_once: true

- name: generate crt
  community.crypto.x509_certificate:
    path: "{{ work_dir | default(playbook_dir + '/tmp') }}/kube-controller-manager.crt"
    privatekey_path: "{{ work_dir | default(playbook_dir + '/tmp') }}/kube-controller-manager.key"
    csr_path: "{{ work_dir | default(playbook_dir + '/tmp') }}/kube-controller-manager.csr"
    provider: ownca
    ownca_path: "{{ work_dir | default(playbook_dir + '/tmp') }}/ca.crt"
    ownca_privatekey_path: "{{ work_dir | default(playbook_dir + '/tmp') }}/ca.key"
    mode: 0644
  delegate_to: localhost
  run_once: true

- ansible.builtin.include_tasks: ../../common/tasks/kubeconfig.yml
  vars:
    kubeconfig_dest: /etc/kubernetes/kube-controller-manager.kubeconfig
    key_file: "{{ work_dir | default(playbook_dir + '/tmp') }}/kube-controller-manager.key"
    crt_file: "{{ work_dir | default(playbook_dir + '/tmp') }}/kube-controller-manager.crt"
    ca_file: "{{ work_dir | default(playbook_dir + '/tmp') }}/ca.crt"
    notified_handler: restart kube-controller-manager
