- name: generate private key
  community.crypto.openssl_privatekey:
    path: "{{ work_dir | default(playbook_dir + '/tmp') }}/service-account.key"
    type: RSA
    size: 2048
    state: present
    mode: 0600
  delegate_to: localhost
  run_once: true

- name: generate csr
  community.crypto.openssl_csr:
    path: "{{ work_dir | default(playbook_dir + '/tmp') }}/service-account.csr"
    privatekey_path: "{{ work_dir | default(playbook_dir + '/tmp') }}/service-account.key"
    common_name: service-accounts
    organization_name: Kubernetes
    key_usage:
      - digitalSignature
    extended_key_usage:
      - serverAuth
      - clientAuth
    state: present
    mode: 0600
  delegate_to: localhost
  run_once: true

- name: generate crt
  community.crypto.x509_certificate:
    path: "{{ work_dir | default(playbook_dir + '/tmp') }}/service-account.crt"
    privatekey_path: "{{ work_dir | default(playbook_dir + '/tmp') }}/service-account.key"
    csr_path: "{{ work_dir | default(playbook_dir + '/tmp') }}/service-account.csr"
    provider: ownca
    ownca_path: "{{ work_dir | default(playbook_dir + '/tmp') }}/ca.crt"
    ownca_privatekey_path: "{{ work_dir | default(playbook_dir + '/tmp') }}/ca.key"
    mode: 0644
  delegate_to: localhost
  run_once: true

- name: copy Kubernetes certifciates
  ansible.builtin.copy:
    src: "{{ work_dir | default(playbook_dir + '/tmp') }}/{{ item }}"
    dest: "/etc/kubernetes/ssl/{{ item }}"
    owner: "{{ kubernetes.user }}"
    group: "{{ kubernetes.group }}"
    mode: 0600
  become: true
  with_items:
    - service-account.crt
    - service-account.key
  notify: restart kube-apiserver
