- name: generate certificate
  include_tasks: cert.yml

- name: copy binary
  ansible.builtin.copy:
    src: "{{ work_dir | default(playbook_dir + '/tmp') }}/kubernetes/server/bin/kube-proxy"
    dest: /usr/local/bin/kube-proxy
    owner: root
    group: root
    mode: 0755
  become: true

- name: copy kube-proxy-config.yaml
  ansible.builtin.template:
    src: templates/kube-proxy-config.yaml
    dest: /etc/kubernetes/kube-proxy-config.yaml
    owner: "{{ kubernetes.user }}"
    group: "{{ kubernetes.group }}"
    mode: 0600
  become: true
  notify: restart kube-proxy

- name: copy kube-proxy.service
  ansible.builtin.template:
    src: templates/kube-proxy.service
    dest: /etc/systemd/system/kube-proxy.service
    owner: "{{ kubernetes.user }}"
    group: "{{ kubernetes.group }}"
  become: true
  notify: restart kube-proxy

- name: enabled kube-proxy.service
  ansible.builtin.systemd:
    name: kube-proxy
    state: started
    enabled: true
    daemon_reload: true
  become: true
