- name: Download package
  ansible.builtin.get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v{{ kubeadm.version }}/bin/linux/amd64/kubeadm
    dest: "{{ work_dir | default(playbook_dir + '/tmp') }}"
    checksum: "{{ kubeadm.checksum }}"
  delegate_to: localhost
  run_once: true

- name: Copy binaries
  ansible.builtin.copy:
    src: "{{ work_dir | default(playbook_dir + '/tmp') }}/kubeadm"
    dest: /usr/local/bin/kubeadm
    owner: root
    group: root
    mode: 0755
  become: true

# - name: Copy kubeadm-config.yaml
#   ansible.builtin.template:
#     src: templates/kubeadm-config.yaml
#     dest: /etc/kubernetes/kubeadm-config.yaml
#     owner: "{{ kubernetes.user }}"
#     group: "{{ kubernetes.group }}"
#     mode: 0600
#   become: true
#   notify: Restart kubeadm

# - name: Copy kubeadm.service
#   ansible.builtin.template:
#     src: templates/kubeadm.service
#     dest: /etc/systemd/system/kubeadm.service
#     owner: "{{ kubernetes.user }}"
#     group: "{{ kubernetes.group }}"
#   become: true
#   notify: Restart kubeadm

# - name: Enabled kubeadm.service
#   ansible.builtin.systemd:
#     name: kubeadm
#     state: started
#     enabled: true
#     daemon_reload: true
#   become: true
